@startUml
UmlDiagram <|-- StructureDiagram
UmlDiagram <|-- BehaviorDiagram
StructureDiagram <|-- ClassDiagram
StructureDiagram <|-- Compound_StructureDiagram
StructureDiagram <|-- ComponentDiagram
StructureDiagram <|-- DeploymentDiagram
StructureDiagram <|-- ObjectDiagram
StructureDiagram <|-- PackageDiagram
BehaviorDiagram <|-- ActivityDiagram
BehaviorDiagram <|--  StateMachineDiagram
BehaviorDiagram <|--  UseCaseDiagram
BehaviorDiagram <|--  InteractionDiagram
InteractionDiagram <|-- CommunicationDiagram
InteractionDiagram <|-- InteractionoverviewDiagram
InteractionDiagram <|-- SequenceDiagram
InteractionDiagram <|-- TimingDiagram
@endUml
