/' http://plantuml.com/ is a drawing tool.
has support for many UML diagrams:
sequence, use case, class, activity, component, state, object
Written in Java and using Graphviz backend for many diagram types. '/
@startuml
'Classes are made with First letter Capitalized
class Dog {
  owner : String
  breed: String
  age : Integer
}

object lassie {
  owner = "Jim"
  breed = "Collie" 
}

package "Public Library" {
  A -- B : "association"
  Customer <-- Product : "one-way association"
  Hammer <|-- CarpenterHammer : generalization
  Company o-- Subsidiary : "weak aggregation"
  Car *-- Wheel : "strong aggregation"
}
Package "used books shop" {
  ' These are for  interfaces
  Specification <|.. Implementation : realization
  SiteSearch <|.. SearchService : realization
}
package Server <<Node>> {

}
@enduml
